# Assignment 25

In [1]:
##ans 1:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


In [2]:
##ans 2:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of elements in list_
for elem in list_:
    print(type(elem))

# Print data types of elements in array_list
for elem in array_list:
    print(elem.dtype)


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<U1
<U1
<U1
<U1
<U1


#ans 3:
 there will be a difference in the data type of the elements present in list_ and array_list if array_list is created with the dtype parameter set to int. In this case, the elements in array_list will be converted to integers.

To print the data types of each element in both list_ and array_list, you can use a for loop to iterate through the elements and the type() function to print the data types. Here's the code:

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in list_
for elem in list_:
    print(type(elem))

# Print data types of elements in array_list
for elem in array_list:
    print(type(elem))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [4]:
#ans 4:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find shape of num_array
shape = num_array.shape
print("Shape of num_array:", shape)

# Find size of num_array
size = num_array.size
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [5]:
#ans 5:
import numpy as np

# Create 3x3 array of zeros
zeros_array = np.zeros(shape=(3, 3))

# Print zeros_array
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#ans 6:
import numpy as np

# Create 5x5 identity matrix
identity_matrix = np.identity(5)

# Print identity_matrix
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
